### ISSUE TITLE
How to catch SmtpClient.SendMailAsync() Exception ? [Help Wanted]

### ISSUE THREAD

**Issue by bufferUnderrun** [unosquare/swan#101]
Hi,

I've read the doc but i don't know how to catch exception from SmtpClient.SendMailAsync() ?

Sometimes, error happen (unknown recipient, server unreachable...) and i want to log them.

Thanks for your help.

**Comment by geoperez** [comment]
can you submit a sample code? I tried something like this:

```
[Test]
        public void InvalidServer_ThrowsSocketException()
        {
            Assert.ThrowsAsync<System.Net.Sockets.SocketException >(async () =>
            {
                var client = new SmtpClient("invalid.local", 587);
                
                await client.SendMailAsync(new SmtpSessionState());
            });
        }
```

And it worked just fine.

**Comment by geoperez** [comment]
hello @bufferUnderrun , any updates?

**Comment by bufferUnderrun** [comment]
Thanks, now i'm using it with proper catching exception.
