### ISSUE TITLE
[Enhancement] Possibility to set data encoding in GetProcessResultAsync

### ISSUE THREAD

**Issue by tenisak** [unosquare/swan#102]
Now the data is decoded using the default coding (for me ANSI). Please add the option to choose another type of encoding. Specifically, it would be great utf-8. (I encountered this when processing the output from ffprobe, which is in utf-8.)

So far, it can be handled by [RunProcessAsync](https://github.com/unosquare/swan#example-1-running-a-process-async). The data can be read as follows:
`Encoding.GetEncoding("utf-8").GetString(data).WriteLine();`

**Comment by geoperez** [comment]
Adding an optional argument won't hurt.

**Comment by geoperez** [comment]
Hi @tenisak , can you clone this branch and test with this method: https://github.com/unosquare/swan/commit/8308e27093b1a0f68340be61a9050499eb43cf80#diff-8f83e8c3b0578bbf841db2ad7cd92a1eR77

**Comment by tenisak** [comment]
Thanks a lot, encoding works! :+1: 
(Problem #103 is also here.)
