### ISSUE TITLE
DependencyContainer bug with singleton registration

### ISSUE THREAD

**Issue by FeelsAmazingMan** [unosquare/swan#106]
This simple exmaple throws a NullReferenceException on [this line](https://github.com/unosquare/swan/blob/master/src/Unosquare.Swan/Components/DependencyContainer.cs#L1269) because `parameters` is set to null by [this line](https://github.com/unosquare/swan/blob/master/src/Unosquare.Swan/Components/DependencyContainer.ObjectFactoryBase.cs#L380).

```
    public class Program
    {
        public static void Main()
        {
            DependencyContainer.Current.Register<IFoo, Foo>().AsSingleton();
            DependencyContainer.Current.Register<IBar, Bar>().AsSingleton();

            var bar = DependencyContainer.Current.Resolve<IBar>();
        }
    }

    public interface IFoo
    {
    }

    public class Foo : IFoo
    {
    }

    public interface IBar
    {
    }

    public class Bar : IBar
    {
        private readonly IFoo _foo;

        public Bar(IFoo foo)
        {
            _foo = foo;
        }
    }
```

**Comment by geoperez** [comment]
The current design calls the method with null because a singleton you have a protected constructor with no arguments. Your example makes sense since the argument is a dependency to be injected.

Let me try to figure out a solution.
