### ISSUE TITLE
Add an SNMP Client

### ISSUE THREAD

**Issue by mariodivece** [unosquare/swan#12]
If possible, add an SNMP client

**Comment by geoperez** [comment]
@mariodivece we have this: https://github.com/unosquare/assetcore/blob/master/Unosquare.AssetCore.ClientLibrary/Core/SnmpClient.cs

Should I move to swan?

**Comment by mariodivece** [comment]
yes but the code is kind of ugly, plus it is missing the GetNext Message which is in fact implemented in http://www.java2s.com/Code/CSharp/Network/SimpleSNMP.htm
