### ISSUE TITLE
Json RFC-8259

### ISSUE THREAD

**Issue by detlefm** [unosquare/swan#138]
The Json.Convert method throws an exception when called with a scalar type like int or string.

Other libs accept a single type and return an array with one item.

It seems the Json Standard had been changed over the years and now a single (non object) value is a valid Josn String.
https://stackoverflow.com/questions/18419428/what-is-the-minimum-valid-json

**Comment by geoperez** [comment]
I updated SWAN JSON to support primitives. Please check version [Swan Lite 0.13.0](https://www.nuget.org/packages/Unosquare.Swan.Lite/0.33.0)
