### ISSUE TITLE
"You need to provide an object or array"

### ISSUE THREAD

**Issue by bender2k14** [unosquare/swan#153]
My application that is using the current version of SWAN (i.e. version 0.34.0) encounters an exception with this as the beginning of the stack trace.

```
System.ArgumentException: You need to provide an object or array
Parameter name: obj
  at Unosquare.Swan.Formatters.Json.Serialize (System.Object obj, System.Boolean format, System.String typeSpecifier, System.Boolean includeNonPublic, System.String[] includedNames, System.String[] excludedNames, System.Collections.Generic.List`1[T] parentReferences) [0x00015] in <840980ba08fc42d585b9dab21160e98b>:0
```

I am a bit confused by this exception message.  In at attempt to reproduce the problem, I would like to see the source code of the method that is throwing the exception.  So far, I have been able to find it.

The closest that I have gotten is [this method](https://github.com/unosquare/swan/blob/c926480656c82975146279c7b0e962ae557de4f6/src/Unosquare.Swan.Lite/Formatters/Json.cs#L128).  It has the correct signature (i.e. name as well as the names, types, and order of arguments) but does not itself throw any exception.  Another clue is that the string `You need to provide an object or array` occurs in the documentation of this method (as well as [this one](https://github.com/unosquare/swan/blob/c926480656c82975146279c7b0e962ae557de4f6/src/Unosquare.Swan.Lite/Formatters/Json.cs#L103) [here](https://github.com/unosquare/swan/blob/c926480656c82975146279c7b0e962ae557de4f6/src/Unosquare.Swan.Lite/Formatters/Json.cs#L61)) alongside a cross reference to `ArgumentException` but occurs no where else in this repository.  But again, I don't see how that string and cross referenced exception type "move" from the documentation into a new exception thrown with that message.

Is there some post complication weaver (like [Fody](https://github.com/Fody/Fody)) being used on this project that converts documentation into executable code?

Can someone help me identify where in this project the above exception is being thrown?

**Comment by geoperez** [comment]
Can you test with the latest version?

**Comment by bender2k14** [comment]
I am already doing so
> My application that is using the current version of SWAN (i.e. version 0.34.0) encounters an exception with this as the beginning of the stack trace.

**Comment by geoperez** [comment]
That exception doesn't exist anymore. We removed when the JSON format changed to support serialize basic values. You can see in the following link when it was removed:

https://github.com/unosquare/swan/commit/8d21a3dba061e3150af4b62db7fd35a9a6c85e54#diff-ddd585931ce5a36b060309e6a53bd8efL138

I need to update the XMLdoc to remove the throw information. For the documentation we already using [docfx](https://dotnet.github.io/docfx/).

Are you sure you are using the latest version?

**Comment by bender2k14** [comment]
Oh, you are correct.

I am using EmbedIO version 1.13.1, which depends on version 0.26.0 of SWAN.  I accidentally thought that I was using the newest version of SWAN because I was looking at the dependencies of the newest version of EmbedIO (which is version 1.16.1).

I will update my application to use the newest version of EmbedIO and see what happens.

Thank you very much for your help! :)

**Comment by geoperez** [comment]
I would recommend you to start using EmbedIO 2.0, we have a RC right now.
