### ISSUE TITLE
Wrong Target Frameworks

### ISSUE THREAD

**Issue by mariodivece** [unosquare/swan#170]
Swan.Lite and Swan don't have matching .net framewaorks. Installing Swan NuGet when targeting .net 4.6.1 will drag netstandard dlls into the solution. Ensure both Swan and Swan.Lite target the SAME set of frameworks and that the .net framework being targeted is 4.6.1 and NOT 4.6.2

**Comment by geoperez** [comment]
@mariodivece please check today nugets.

**Comment by geoperez** [comment]
Can I close this issue?
