### ISSUE TITLE
The SerializerOptions.TypeSpecifier deserialization is not used and this support should be added

### ISSUE THREAD

**Issue by delphidoc** [unosquare/swan#173]
{
    "$type": "V3C.Entity.ServerConfigInfo",
    "Config": 
    {
        "$type": "V3C.Entity.ServerConfig",
        "Interval": 30,
        "WebServerPort": 9090,
        "MessagePort": 9091,
        "UdpPort": 9092
    }
}

**Comment by geoperez** [comment]
Hi @delphidoc , can you elaborate? Probably with sample code?

**Comment by geoperez** [comment]
Status?
