### ISSUE TITLE
`IDataDictionary<TKey, TValue>` should expose its full potential

### ISSUE THREAD

**Issue by rdeago** [unosquare/swan#184]
As per unosquare/embedio#335, `IDataDictionary<TKey,TValue>` can (and should) be changed to derive from both `IDictionary<TKey,TValue>` and `IReadOnlyDictionary<TKey,TValue>`, adding only the `IsEmpty` property.

Besides being consistent with functionality currently present in both `DataDictionary<TKey,TValue>` and `ConcurrentDataDictionary<TKey,TValue>`, thus only requiring a change to the interface, this will have the side effect of making EmbedIO session data enumerable.

It will be a breaking change, though, because of the changed interface.

**Comment by geoperez** [comment]
Can I close this issue?
