### ISSUE TITLE
Broken API Links in GitHub Readme?

### ISSUE THREAD

**Issue by pha3z** [unosquare/swan#189]
All (or a ton of???) of the links I'm trying to click for the various classes in the API on the GitHub Readme take me to 404s. Where can I access that information?

**Comment by MarcoLPR** [comment]
Hi @pha3z 
Sorry for the inconvenience, I'm going to work on this right now.
I will keep you updated.

**Comment by MarcoLPR** [comment]
Ready, I double checked all the links, all must be working.
If you find any other broken link, please, contact me, I'm glad to help.

**Comment by pha3z** [comment]
AWESOME!  Thank you! :)

By the way, did you remove the SNMP link? I don't see it. I'm guessing that's no longer part of the library.  If it's not, do you have an SNMP library your recommend?

**Comment by MarcoLPR** [comment]
Yes, we don't have that anymore, but you can used it in the version 1.x of SWAN

**Comment by pha3z** [comment]
Where would I go to get swan 1.x?  And also, what was the reason for removal?  I'm definitely going to need a reliable SNMP client for a project I'm on.

**Comment by MarcoLPR** [comment]
If you are using the Visual Studio, the Nuget Packages manager let you select which version you want to install
![image](https://user-images.githubusercontent.com/25437790/63595287-2b07e680-c57e-11e9-8f40-6041daacde27.png)

Or this is the link to the SWAN repository at version 1.3.1
https://github.com/unosquare/swan/tree/628e29635a5cc2b4d3216eff86b0a1b988b91d25

**Comment by pha3z** [comment]
Thank you!

Just curious, why was the SNMP module removed from Swan 2?

**Comment by geoperez** [comment]
We trimmed a little bit the number of classes and extension methods, to focus on, what we think, are the most valuables components.

There is not much SNMP development these dates.
