### ISSUE TITLE
NuGetPackage for Swan Lite does not contain net461 assembly

### ISSUE THREAD

**Issue by mariodivece** [unosquare/swan#228]
Since a few releases of the NuGet package for SWAN Lite, I notices a bunch of assemblies are dumped to the output of build that use it but target net461. To avoid this, please add the following to the SWAN Lite csproj file when publishing to NuGet:
`<TargetFrameworks>netstandard2.0;net461</TargetFrameworks>`

The most recent versions of visual studio correctly reference the correct build assemblies (in the case of SWAN -- not lite)

**Comment by geoperez** [comment]
Adding the NET461 framework will introduce a dependency on SWAN Lite.

https://www.nuget.org/packages/System.ValueTuple/

**Comment by geoperez** [comment]
I just published version 2.5.1 with the new target.
