### ISSUE TITLE
JSON serializer does not serialize strings correctly

### ISSUE THREAD

**Issue by rdeago** [unosquare/swan#237]
**Describe the bug**
`Swan.Formatters.Json.Serialize("Hello world!")` should returns a JSON-serialized string:
```
"Hello world!"
```
Instead, it returns:
```
Hello world!
```

**To Reproduce**
https://dotnetfiddle.net/LIS41V

**Expected behavior**
When passing a string to a JSON serializer, for it to actually serialize it seems to be a reasonable expectation.

**Comment by geoperez** [comment]
You are right, Newtonsoft JSON returns a quoted string.
