### ISSUE TITLE
Logger throw System.PlatformNotSupportedException on Xamarin.Forms.Android

### ISSUE THREAD

**Issue by TSIoT** [unosquare/swan#244]
**Describe the bug**
Throw exception every time when use the Swan.Logger. To be precise: this line cause the exception: [https://github.com/unosquare/swan/blob/3bb63a693c93acc5066ddeddf850ae26a565d84f/src/Swan.Lite/Terminal.cs#L132](url)

Here is the detial of exception:
{System.PlatformNotSupportedException: Operation is not supported on this platform.  at System.Console.get_WindowHeight () [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/corlib/System/Console.cs:879   at Swan.Terminal.get_IsConsolePresent () [0x00017] in <06bfbc2671434da79b826d112de2988b>:0 }

**To Reproduce**
Use Swan.Logging like "LogSomeInfo".Info(LogSource); Then it throw this exception.

**Expected behavior**
No exception even in debug mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/17898508/81548661-33c07700-93b0-11ea-8722-a40c8c71bf7c.png)
![image](https://user-images.githubusercontent.com/17898508/81549142-dd076d00-93b0-11ea-93f2-030675136a73.png)

**Desktop (please complete the following information):**
 - OS: Windows10

**Smartphone (please complete the following information):**
 - Device: Sony XPERIA (G8342)
 - OS: Android 9.0

**Additional context**
Is that possible use something like "#if MONOANDROID" to avlid this exception?

**Comment by geoperez** [comment]
Hello, the preprocessor directives will not work because you are not compiling SWAN in your project. But I can add a check for the `PlatformNotSupportedException` exception in the initialization of the ConsoleLogger.

**Comment by geoperez** [comment]
In fact, the check is there, what do you see it's only the result of that check. You might ignore the exception.

**Comment by TSIoT** [comment]
Hi @geoperez ,
How about change the code in Swan.Terminal.IsConsolePresent to
`
public static bool IsConsolePresent
{
    get
    {
        if (_isConsolePresent != null)
            return _isConsolePresent.Value;

        _isConsolePresent = Console.OpenStandardInput(1) != Stream.Null;

        return _isConsolePresent.Value;
    }

    set
    {
        _isConsolePresent = value;
    }
}
`
or
add a setter let user can use `Swan.Terminal.IsConsolePresent = false;` to avoid the exception. 
`
set
{
   _isConsolePresent = value;
}
`
So not need to use exception drive behavior.

**Comment by TSIoT** [comment]
um...sorry, I just realize `Console.OpenStandardInput(1) != Stream.Null;` only work for windows not work for Xamarin.Android. And setter still have issue because constructor of Terminal will use getter first.
