### ISSUE TITLE
Unix signals not working if Swan is loaded

### ISSUE THREAD

**Issue by mcrossley** [unosquare/swan#246]
Not sure if this a bug, or my lack of knowledge.

I had an issue in my main application which is targeting .Net Framework and designed to run under .Net or Mono.
I have reproduced this in minimum code app (below) targeting .Net 4.6.1 that does nothing except listen for Ctrl-C.

Under Windows I use SetConsoleCtrlHandler() to capture Ctrl-C and Close Window and perform a clean close. This works fine under .Net with Swan.

Under Lnux/mono I start a thread to monitor for Unix signals (SIGINT and SIGTERM). This works OK until Swan is loaded.

```C#
using System;
using System.Reflection;
using System.Threading;
using Swan;

namespace test1
{
	class Program
	{
		public static bool exitSystem = false;
		static void Main(string[] args)
		{

			if (Type.GetType("Mono.Runtime") != null)
			{
				// Use reflection, so no attempt to load Mono dll on Windows

				Assembly _posixAsm;
				Type _unixSignalType, _signumType;
				MethodInfo _unixSignalWaitAny;

				_posixAsm = Assembly.Load("Mono.Posix, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756");
				_unixSignalType = _posixAsm.GetType("Mono.Unix.UnixSignal");
				_unixSignalWaitAny = _unixSignalType.GetMethod("WaitAny", new[] { _unixSignalType.MakeArrayType() });
				_signumType = _posixAsm.GetType("Mono.Unix.Native.Signum");

				Array _signals = Array.CreateInstance(_unixSignalType, 2);
				_signals.SetValue(Activator.CreateInstance(_unixSignalType, _signumType.GetField("SIGINT").GetValue(null)), 0);
				_signals.SetValue(Activator.CreateInstance(_unixSignalType, _signumType.GetField("SIGTERM").GetValue(null)), 1);

				Thread signal_thread = new Thread(delegate ()
				{
					// Wait for a signal to be delivered
					var id = (int)_unixSignalWaitAny.Invoke(null, new object[] { _signals });

					Console.WriteLine("\nExiting system due to external signal: " + (id == 0 ? "SIGINT" : "SIGTERM"));

					exitSystem = true;
				});

				signal_thread.Start();
			}
			// Uncomment me to break Unix Signals
			//Terminal.WriteLine("SWAN loaded");

			Console.WriteLine("Type Ctrl-C to terminate");
			while (!exitSystem)
			{
				Thread.Sleep(500);
			}

			Console.WriteLine("done");
			Thread.Sleep(2000);
			Environment.Exit(1);
		}
	}
}
```

Can you tell me why the signals no longer work as soon as you load Swan?

**Comment by geoperez** [comment]
This is really odd, I can't tell a reason why this is happening. Do you try .NET Core Linux? Or only Mono?

**Comment by mcrossley** [comment]
My main application is quite large and complex and bound to .Net for the moment because of some of the third party libraries it uses. Swan is actually being loaded as a dependency for EmbedIO.

The problem is there from Swan version 0.38.0 (the earliest version I have used), the test app above is using the latest version.

I could try creating the minimal test app as Core and see if it changes, but that will not solve my primary issue.

**Comment by mcrossley** [comment]
I have found a workaround for this.

Under mono, I am now just listening for Unix SIGTERM, and adding a Console.CancelKeyPress function to capture Ctrl-C
