### ISSUE TITLE
If an app using Swan has its output redirected it throws an exception 

### ISSUE THREAD

**Issue by smitha-cgi** [unosquare/swan#250]
To reproduce, build a simple command line app that references the swan library. Then execute that app via another app which does the following:

```
var process = new Process(); 
process.StartInfo.FileName = path_to_simple_app;
process.StartInfo.RedirectStandardOutput = true;
process.OutputDataReceived += OutputDataReceived;
process.StartInfo.UseShellExecute = false;
process.Start();
```

The following exception occurs:

> Unhandled Exception: System.TypeInitializationException: The type initializer for 'Swan.Logging.Logger' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Swan.Terminal' threw an exception. ---> System.IO.IOException: The handle is invalid.
> 
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.__Error.WinIOError()
>    at System.Console.set_CursorVisible(Boolean value)
>    at Swan.Terminal..cctor() in C:\temp\swan-master\src\Swan.Lite\Terminal.cs:line 42
>    --- End of inner exception stack trace ---
>    at Swan.Terminal.get_IsConsolePresent()
>    at Swan.Logging.Logger..cctor() in C:\temp\swan-master\src\Swan.Lite\Logging\Logger.cs:line 22
>    --- End of inner exception stack trace ---
>    at Swan.Logging.Logger.UnregisterLogger[T]()
>    at ConsoleApp1.Program.Main(String[] args) in C:\temp\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 13

Seems like Console.WindowHeight still returns a value > 0 in this situation, which means the test for whether a console is present passes. The simplest fix seems to be changing Terminal.cs line 42 from this:

`Console.CursorVisible = false;    `               

to this:

```
try
{
    Console.CursorVisible = false;
}
catch
{
    _isConsolePresent = false;
}
```

**Comment by m0nzderr** [comment]
Is there any temporary workaround? I'm using a library that in turn uses Swan.Logging under the hood... It breaks completely without console. Even when calling Logger.NoLogging().
