### ISSUE TITLE
Log messages are missed

### ISSUE THREAD

**Issue by Temtaime** [unosquare/swan#257]
Hello. There's major flaw in logging:

https://github.com/unosquare/swan/blob/master/src/Swan.Logging/Logging/Logger.cs#L688

```
    public static async Task Main() {
        Logger.Info("hello");

        //await Task.Delay(1000);
    }
```

There's no output. If you uncomment the line, then it logs ok.
There's no way to get all the tasks and wait for them before app's shutdown. 
Even Task.Delay may not be enough.
So there's no way to differ app crash from normal exit.

**Comment by mariodivece** [comment]
Yep, noticed that. Just fixed it.

**Comment by Temtaime** [comment]
Thanks, update please deps version in embedio too :)

**Comment by asesidaa** [comment]
Hi, has this issue been fixed in the released version? As I am facing the same issue with version 6.0.2-beta.69 (which is the latest one from nuget). I have to add `Console.ReadKey(true);` as a workaround
