### ISSUE TITLE
Any roadmap for next version of SWAN?

### ISSUE THREAD

**Issue by rdeago** [unosquare/swan#262]
I'm currently working on a PR that will advance EmbedIO to version 4. Since there has been no real feedback to [my request for comments](https://github.com/unosquare/embedio/issues/546) so far, I'll probably change EmbedIO's target platform from .NET Standard 2.0 to .NET 6.

Now the problem is, which version of SWAN should EmbedIO 4.0 depend upon? The [Unosquare.Swan.Lite4](https://www.nuget.org/packages/Unosquare.Swan.Lite4) package does not look like a good choice, considering that version 6 packages [have been out for a while](https://www.nuget.org/packages?q=Swan).

@mariodivece, is a non-preview version 6 of SWAN going to be published any soon?

**Comment by geoperez** [comment]
Hey @rdeago, the future of SWAN will probably be only Swan.Data and the things behind it (like Reflection cache, etc). EmbedIO should probably let go SWAN and has a fresh start.

I'm closing this issue now. Let me know if you have further questions.

**Comment by rdeago** [comment]
Thanks for the info @geoperez. Even if I definitely saw it coming, an official confirmation is always a good thing.
