### ISSUE TITLE
Unit testing is broken

### ISSUE THREAD

**Issue by geoperez** [unosquare/swan#266]
Unit testing is broken, please check why they are failing and try to fix them. If the issue is located in the library, just report back.

**Comment by Brianx03** [comment]
I found that the following tests from CollectionProxyTest are not running
RemoveAtWorksAsExpected 
LastWorksAsExpected 
KeysWorksAsExpected 
IndexOfWorksAsExpected 
EnumeratorsWorksAsExpected 
CountWorksAsExpected 
CopyToWorksAsExpected
ConversionWorksAsExpected 
ContainsKeyWorksAsExpected 

The error message seems to be the same for all of them:
Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\System.Runtime.CompilerServices.Unsafe.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[31232] testhost.exe' has exited with code 3221225477 (0xc0000005) 'Access violation'.

I´m investigating the cause
