### ISSUE TITLE
API CopyMemory in kernel32.dll is not supported for this application type. Unosquare.Swan.dll calls this API.

### ISSUE THREAD

**Issue by guidowalter** [unosquare/swan#86]
Hi,

we use Embed IO in one of our apps, which uses SWAN. Wenn we try to publish the app to the Windows Store, we get the error "API CopyMemory in kernel32.dll is not supported for this application type. Unosquare.Swan.dll calls this API." 

We checked the code for Embed IO and did not found any reference to CircularBuffer() which causes the problem in SWAN:

        [DllImport("kernel32")]
        public static extern void CopyMemory(IntPtr destination, IntPtr source, uint length);

As a workaround for us we code remove the CircularBuffer Class from SWAN and resubmit but this is not a long term solution.

Could you implement a managed alternative and not using the unmanaged Windows API anymore?

Thanks and regards

Guido

**Comment by guidowalter** [comment]
Maybe Buffer.MemoryCopy  (https://docs.microsoft.com/de-de/dotnet/api/system.buffer.memorycopy?view=netframework-4.7.1) would be possible?

**Comment by geoperez** [comment]
Hi @guidowalter, we are checking if EmbedIO can run with SWAN Lite. The Lite version doesn't have the `CircularBuffer` component.

**Comment by geoperez** [comment]
Please check new [EmbedIO nuget](https://www.nuget.org/packages/EmbedIO/1.13.0)
