### ISSUE TITLE
New .csproj with SDK "Microsoft.NET.Sdk.Web" fail to load

### ISSUE THREAD

**Issue by robertsundstrom** [unosquare/swan#96]
Cannot deploy ASP.NET Core project with SSHDeploy which depends on SWAN. 

```
Unhandled Exception: System.ArgumentException: Project file is not of the new .csproj type.
     at Unosquare.Swan.Components.CsProjFile`1..ctor(Stream stream, Boolean leaveOpen)
     at Unosquare.Labs.SshDeploy.Program.Main(String[] args)
```

It is because the ```CsProjFile``` class checks for ```Sdk="Microsoft.NET.Sdk"```, and assumes that it is what makes it the new .csproj-format, but there is also ```Microsoft.NET.Sdk.Web``` for web projects.

Is that really the only way to check if it is the new csproj-format?

**Comment by geoperez** [comment]
Tomorrow I will release a new nuget.

**Comment by mariodivece** [comment]
@geoperez could you also update our sshdeploy tool and release a new nuget?

**Comment by geoperez** [comment]
Yes ;)
